<div class="title-area">
    <h2 class="title-text resume-title-text">
        HSIN-HUA YANG
        <a class="resume-download" href="https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL2IvcyFBbWV4YVRkZTBJekhoTkJPemNvQnhwTXBQT3laQVE_ZT1Ja25mUTc/root/content" data-toggle="tooltip" data-placement="right" title="Download">
            <i class="fas fa-download" style="font-size:25px;color:DarkOrange;"></i>
        </a>
    </h2>
</div>
<br/>
<div class="content-area resume-content-area">
    <div class="resume-content-group">
        <h4>
            EDUCATION
        </h4>
        <ul>
            <li>
                BS, Electrophysics, National Chiao Tung University, Taiwan
                <span class="resume-li-time">2016</span>
            </li>
        </ul>
    </div>
    <div class="resume-content-group">
        <h4>
            EXPERIENCE
        </h4>
        <ul>
            <li>
                Undergraduate Research
                <span class="resume-li-time">2014－2015</span>
                <div class="resume-li-detail">
                Under Associate Professor Jung-Jung Su, Department of Elctrophysics, NCTU
                <br/>
                Subject: many-body system
                <ul>
                    <li>
                        Learn operation of MATLAB
                    </li>
                    <li>
                        Understand problem-solving skills
                    </li>
                    <li>
                        Acquire communication skills and systematic thinking
                    </li>
                </ul>
                </div>
            </li>
            <li>
                Tutor of senior high school student in Mathematics and Physics
                <span class="resume-li-time">2013－2017</span>
            </li>
            <li>
                A member of student association
                <span class="resume-li-time">2013－2014</span>
                <div class="resume-li-detail">
                    <ul>
                        <li>
                            Conduct several activities
                        </li>
                        <li>
                            Understand problem-solving skills
                        </li>
                        <li>
                            Acquire communication skills and systematic thinking
                        </li>
                    </ul>
                </div>
            </li>
            <li>
                A team member in volleyball club
                <span class="resume-li-time">2012－2015</span>
            </li>

        </ul>
    </div>
    <div class="resume-content-group">
        <h4>
            EMPLOYMENT
        </h4>
        <ul>
            <li>
                Elo Touch Solutions, Taiwan
                <span class="resume-li-time">2016－2018</span>
                <br/>
                Test Engineer
                <div class="resume-li-detail">
                    <ul>
                        <li>
                            Training for touch principles in U.S. headquarter
                        </li>
                        <li>
                            Survey purchase of new linear test machine
                        </li>
                        <li>
                            Write and compile document for directions in test procedures
                        </li>
                        <li>
                            Define test specs
                        </li>
                        <li>
                            Guide for company booth in COMPUTEX TAIPEI 2017 and 2018
                        </li>
                        <li>
                            Code by python for processing csv files into visual graphs
                        </li>
                        <li>
                            Cooperate with team members
                        </li>
                        <li>
                            Help interviews for new colleague
                        </li>
                    </ul>
                </div>
            </li>
            <li>
                LYC株式会社, Japan
                <span class="resume-li-time">2018－2019, 06</span>
                <br/>
                Programmer
                <div class="resume-li-detail">
                    <ul>
                        <li>
                            Programming with Python for dealing json files
                        </li>
                        <li>
                            Execute python scripts in remote Linux server system
                        </li>
                        <li>
                            Familiarize commands in SQL (MSSQL, DB2)
                        </li>
                        <li>
                            Cooperate with colleagues in Japanese
                        </li>
                    </ul>
                </div>
            </li>
            <li>
                IQBETA LLC., Japan
                <span class="resume-li-time">2019, 07－2020, 04</span>
                <br/>
                Internship
                <div class="resume-li-detail">
                    <ul>
                        <li>
                            Collect test data for face recognition project
                        </li>
                        <li>
                            Analyze test results for face recognition project
                        </li>
                        <li>
                            Write python code for visualizing results
                        </li>
                    </ul>
                </div>
            </li>
            <li>
                いえらぶGROUP, Japan
                <span class="resume-li-time">2020, 02－current</span>
                <br/>
                Part-time in Homepage Develop Team
                <div class="resume-li-detail">
                    <ul>
                        <li>
                            Develop and maintain websites for real estate by php, js, html
                        </li>
                        <li>
                            Research for bugs in codes and fix them
                        </li>
                        <li>
                            Improve process speed in website from fixing low efficient codes
                        </li>
                        <li>
                            Update php environment: from php5.X to php7.0
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
</div>

<script>
    $(function () {
        $('.resume-download').tooltip();
    });
</script>
