<?php
$navbarDefArr = [
    'home' => [
        'urlKey' => 'home',
        'action' => 'index'
    ],
    'about' => [
        'urlKey' => 'application',
        'action' => 'about'
    ],
    'links' => [
        'urlKey' => 'application',
        'action' => 'links'
    ],
    'game' => [
        'urlKey' => 'game',
        'action' => 'game'
    ],
    'tutorial' => [
        'urlKey' => 'tutorial',
        'action' => 'index'
    ]
];
?>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <img src="<?= $this->basePath('img/navbar_smile.svg') ?>" height="28" alt="Cindy's Website"/>&nbsp;Cindy's Website
            </a>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <?php foreach ($navbarDefArr as $urlName => $urlData) { ?>
                    <li class="nav-item active">
                        <a class="nav-link" href="<?= $this->url($urlData['urlKey'], ['action' => $urlData['action']]) ?>">
                            <?= $urlName ?>
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                <?php } ?>
            </ul>
        </div>
    </div>
</nav>
