<?php
$supportedLanguageArr = ['English', 'Japanese', 'Chinese'];
$gameNameArr = [
    'Tic-Tac-Toc' => 'tictactoc',
    "Conway's Game of Life" => 'gameoflife'];
$dropDownArr = [
    'game' => [
        'positionClass' => 'mr-auto',
        'content' => [
            'Tic-Tac-Toc',
            "Conway's Game of Life"
        ]
    ],
    'language' => [
        'positionClass' => 'ml-auto',
        'content' => [
            'English',
            'Japanese',
            'Chinese'
        ]
    ]
];

$currentUrlName = $_SERVER['REQUEST_URI'];
if (!basename($currentUrlName)) {
    $currentUrlName = 'home';
} else {
    $currentUrlName = basename($currentUrlName);
}
$navbarDefArr = [
    'home' => [
        'urlKey' => 'home',
        'action' => 'index'
    ],
    'about' => [
        'urlKey' => 'application',
        'action' => 'about'
    ],
    'accomplishment' => [
        'urlKey' => 'application',
        'action' => 'accomplishment'
    ],
    'links' => [
        'urlKey' => 'application',
        'action' => 'links'
    ]
];
?>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <img src="<?= $this->basePath('img/navbar_smile.svg') ?>" height="28" alt="Cindy's Website"/>&nbsp;Cindy's Website
            </a>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <?php foreach ($navbarDefArr as $urlName => $urlData) { ?>
                    <li class="nav-item <?= ($urlName == $currentUrlName) ? 'active' : '' ?>">
                        <a class="nav-link" href="<?= $this->url($urlData['urlKey'], ['action' => $urlData['action']]) ?>">
                            <?= $urlName ?>
                        </a>
                    </li>
                <?php } ?>
                <li class="nav-item <?= (basename(dirname($_SERVER['REQUEST_URI'])) == 'game') ? 'active' : '' ?> dropdown">
                    <a class="nav-link dropdown-toggle" href="javascript:void(0);" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        game
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <?php foreach ($gameNameArr as $gameName => $gameLink) { ?>
                            <a class="dropdown-item" href="<?= $this->url('game', ['action' => $gameLink]) ?>">
                                <?= $gameName ?>
                            </a>
                        <?php } ?>
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="javascript:void(0);" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        language is still under working
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <?php foreach ($supportedLanguageArr as $supportedLanguage) { ?>
                            <a class="dropdown-item" href="javascript:void(0);">
                                <?= $supportedLanguage ?>
                            </a>
                        <?php } ?>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

<script>
    $(function() {
        $('.dropdown-toggle').dropdown();
    });
</script>
