<?= $this->doctype() ?>
<?php
if ($_SERVER['REQUEST_URI'] == '/' || basename($_SERVER['REQUEST_URI']) == 'index') {
    header('Location:' . '/index' . '/' . $this->langFlag);
    exit();
}
require_once 'footer/footer_form_process.php';
?>
<html lang="<?= $this->langFlag ?>">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('cindy50633')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        if (basename(dirname($_SERVER['REQUEST_URI'])) == 'game') {
            $this->headLink(['rel' => 'shortcut icon',
                             'type' => 'image/vnd.microsoft.icon',
                             'href' => $this->basePath() . '/img/site_fish.svg',
                             'sizes' => '30x16'])
                ->prependStylesheet($this->basePath('css/game.css'));
            // $this->inlineScript()
            //     ->prependFile($this->basePath('js/life.js'));
        }
        if (basename(dirname($_SERVER['REQUEST_URI'])) == 'resume') {
            $this->headLink(['rel' => 'shortcut icon',
                             'type' => 'image/vnd.microsoft.icon',
                             'href' => $this->basePath() . '/img/site_fish.svg',
                             'sizes' => '30x16'])
                ->prependStylesheet($this->basePath('css/about_resume.css'));
            // $this->inlineScript()
            //     ->prependFile($this->basePath('js/life.js'));
        }
        if (basename(dirname($_SERVER['REQUEST_URI']))) {
            $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/site_fish.svg','sizes' => '30x30'])
                ->prependStylesheet($this->basePath('css/recommend.css'));
        }
        if (basename($_SERVER['REQUEST_URI']) == 'tictactoe') {
            $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/site_fish.svg','sizes' => '30x30'])
                ->prependStylesheet($this->basePath('css/game.css'));
        }
        ?>

        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/site_fish.svg','sizes' => '30x30'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/footer.css'))
            ->prependStylesheet($this->basePath('css/header.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/content.css'))
            // ->prependStylesheet($this->basePath('css/footer.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile('https://kit.fontawesome.com/a076d05399.js')
        ?>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
            ->prependFile($this->basePath('js/popper.min.js'))
        ?>
    </head>
    <body>
        <?= $this->partial('header/header.phtml') ?>
        <div class="container">
            <?= $this->content ?>
            <br/>
            <br/>
            <hr style="border:0.1px dotted DarkOrange;">
            <?= $this->partial('footer/footer.phtml') ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
