<?= $this->doctype() ?>

<html lang="<?= $this->langFlag ?>">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('cindy50633')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        if (basename(dirname($_SERVER['REQUEST_URI'])) == 'game') {
            $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/site_smile.svg'])
                ->prependStylesheet($this->basePath('css/game.css'));
            // $this->inlineScript()
            //     ->prependFile($this->basePath('js/life.js'));
        }
        if (basename($_SERVER['REQUEST_URI']) == 'tictactoe') {
            $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/site_smile.svg'])
                ->prependStylesheet($this->basePath('css/game.css'));
        }
        ?>

        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/site_smile.svg'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/content.css'))
            ->prependStylesheet($this->basePath('css/footer.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile('https://kit.fontawesome.com/a076d05399.js')
        ?>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
            ->prependFile($this->basePath('js/popper.min.js'))
        ?>
    </head>
    <body>
        <?= $this->partial('header/header.phtml') ?>
        <div class="container">
            <?= $this->content ?>
            <br/>
            <br/>
            <hr>
            <?= $this->partial('footer/footer.phtml') ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
