<?php
$yourLuckyNum = rand(0, 11);
?>

<?php
if ($yourLuckyNum == 0) {
    $today = new DateTime('now');
    $einsteinBirthday = new DateTime('1879-3-14');
    $einsteinAge = date_diff($today, $einsteinBirthday);
?>
    Today is <?= $today->format('Y-m-d') ?>.
    If Einstein were alive today,
    he would be <?= $einsteinAge->format('%Y') ?> years old.
<?php } ?>

<?php if ($yourLuckyNum == 1) { ?>
    Do you know <b><i>Schrödinger's cat</i></b>?
    You would not know if the cat was dead or alive until you opened the box.
    <br/>
    Mmmmmm... Why don't they use dogs for this thought experiment.
<?php } ?>

<?php if ($yourLuckyNum == 2) { ?>
    Do you feel that Weekends always end faster than Weekdays?<br/>
    These all credit on relativity........
    You do know I'm just joking, right?
<?php } ?>

<?php if ($yourLuckyNum == 3) { ?>
    With the evolution of technology, there are a lot of free sources for learning now on Internet!<br/>
    Please click the "recommend sources" page for those I recommend!
<?php } ?>

<?php if ($yourLuckyNum == 4) { ?>
    Bubble tea is made from the powder of sweet potato.<br/>
    I am not kidding, ok?
<?php } ?>

<?php if ($yourLuckyNum == 5) { ?>
    Newton's 1<sup>st</sup> Law:<br/>
    A body at rest wants to stay at rest.<br/>
    <img src="<?= $this->basePath('img/footer_puzzle_newton_first_law.svg') ?>" height="100"></img>
<?php } ?>

<?php if ($yourLuckyNum == 6) { ?>
    I have potential!<br/><br/>
    <img src="<?= $this->basePath('img/footer_puzzle_potential.svg') ?>" height="100"></img>
<?php } ?>

<?php if ($yourLuckyNum == 7) { ?>
    To be, or not to be.<br/><br/>
    <img src="<?= $this->basePath('img/footer_puzzle_2b_or_not_2b.svg') ?>" height="100"></img>
<?php } ?>

<?php if ($yourLuckyNum == 8) { ?>
    A neutron walked into a bar and asked, "How much for a drink?"<br/>
    The bartender replied, "For you, no charge."
<?php } ?>

<?php if ($yourLuckyNum == 9) { ?>
    E = mc<sup>2</sup>
<?php } ?>

<?php if ($yourLuckyNum == 10) { ?>
    Why was <b><i>Heisenberg's</i></b> wife unhappy?<br/>
    Whenever he had the energy, he didn't have the time.
<?php } ?>

<?php if ($yourLuckyNum == 11) { ?>
    A photon checks into a hotel.<br/>
    The clerks asks, "Do you have any luggage?"<br/>
    The photon replies, "Nope. I'm traveling light."
<?php } ?>
