<?php
use Common\CommonController;
require_once getcwd() . '/module/Application/view/layout/view_lang_define/footer_define.php';
require_once 'footer_form_modal.phtml';

$fishSizeArr = [25, 35, 45, 55];
$fishOpacityArr = [0.4, 0.5, 0.6, 0.7, 0.9];
$fishRightHeightArr = [10, 25, 45, 60, 75, 90];
$fishLeftHeightArr = [10, 25, 45, 60, 75, 90];
$randRightFishNum = rand(3, 6);
$randLeftFishNum = rand(3, 6);
?>

<div class="right-edge">
    <?php for ($i = 0; $i < $randRightFishNum; $i++) { ?>
        <?php
        $currentFishSize = $fishSizeArr[array_rand($fishSizeArr)];
        $currentOpacity = $fishOpacityArr[array_rand($fishOpacityArr)];
        $currentKey = array_rand($fishRightHeightArr);
        $currentHeight = $fishRightHeightArr[$currentKey];
        unset($fishRightHeightArr[$currentKey]);
        ?>
        <a class="icon" href="javascript:void(0);" style="position: inherit; top:<?= $currentHeight ?>%; transform: rotate(<?= rand(0, 365) ?>deg); opacity:<?= $currentOpacity ?>;">
            <i class="fas fa-fish side-fish" style="font-size:<?= $currentFishSize ?>px;"></i>
        </a>
    <? } ?>
</div>
<div class="left-edge">
    <?php for ($i = 0; $i < $randLeftFishNum; $i++) { ?>
        <?php
        $currentFishSize = $fishSizeArr[array_rand($fishSizeArr)];
        $currentOpacity = $fishOpacityArr[array_rand($fishOpacityArr)];
        $currentKey = array_rand($fishLeftHeightArr);
        $currentHeight = $fishLeftHeightArr[$currentKey];
        unset($fishLeftHeightArr[$currentKey]);
        ?>
        <a class="icon" href="javascript:void(0);" style="position: inherit; top:<?= $currentHeight ?>%; transform: rotate(<?= rand(0, 365) ?>deg); opacity:<?= $currentOpacity ?>;">
            <i class="fas fa-fish side-fish" style="font-size:<?= $currentFishSize ?>px;"></i>
        </a>
    <? } ?>
</div>

<span class="fixed-contact-bottom">
    <div class="btn-group" role="group" aria-label="Contact Button Group">
        <button type="button" class="popup btn btn-orange" onclick="popup()">
            <?= $contactBottomTitle[$this->langFlag] ?>
            <span class="popuptext btn-orange" id="popup-area">
                <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                    <span class="contact-icon-group" data-toggle="tooltip" data-placement="top" title="Facebook">
                        <a class="icon" href="http://m.me/cindy50633" target="_blank">
                            <i class="fab fa-facebook-square contact-icon-group ml-3 mr-2" style="font-size:36px"></i>
                        </a>
                    </span>
                    <span class="contact-icon-group" data-toggle="tooltip" data-placement="top" title="Linkedin">
                        <a class="icon" href="https://www.linkedin.com/in/cindy-yang-05b1b237" target="_blank">
                            <i class="fab fa-linkedin contact-icon-group mx-2" style="font-size:36px"></i>
                        </a>
                    </span>
                    <span class="contact-icon-group" data-toggle="tooltip" data-placement="top" title="Mail">
                        <a class="icon" href="javascript:void(0);" data-toggle="modal" data-target="#mailFormModal" data-whatever="cindy50633@gmail.com">
                            <i class="fas fa-envelope-square ml-2 mr-3" style="font-size:36px"></i>
                        </a>
                    </span>
                </div>
            </span>
        </button>
        <button type="button" class="btn btn-orange p-1">
            <span class="contact-icon-group" data-toggle="tooltip" data-placement="bottom" title="Github">
                <a class="icon" href="https://github.com/cindy50633" target="_blank">
                    <i class="fab fa-github" style="font-size:45px"></i>
                </a>
            </span>
        </button>
    </div>
</span>

<footer>
    <p id="footer-text">
        <?php require_once 'footer_puzzle.phtml'; ?>
    </p>
</footer>


<script>

    function popup() {
        $('#popup-area').toggleClass("show");
    }

    $(document).mouseup(function(e) {
        var $contactBottom = $('.fixed-contact-bottom');
        // if the target of the click isn't the $popupBtn nor a descendant of the $popupBtn
        if (!$contactBottom.is(e.target) && $contactBottom.has(e.target).length === 0) {
            $('#popup-area').removeClass("show");
        }
    });

    // $('#mailFormModal').on('show.bs.modal', function (event) {
    //   var button = $(event.relatedTarget) // Button that triggered the modal
    //   var recipient = button.data('whatever') // Extract info from data-* attributes
    //   // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
    //   // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
    //   var modal = $(this)
    //   modal.find('.modal-title').text('New message to ' + recipient)
    //   modal.find('.modal-body input').val(recipient)
    // })

    $(function () {
        $('.contact-icon-group').tooltip();

        $('.side-fish').on('click', function() {
            let random_boolean = Math.random() >= 0.5;
            let fish_height = $(this).parent().height();
            let fish_weight = $(this).parent().width();
            if ($(this).hasClass('fa-fish')) {
                $(this).removeClass('fa-fish');
                if (random_boolean) {
                    $(this).addClass('fa-sushi-light');
                } else {
                    $(this).addClass('fa-sushi-dark');
                }
                $(this).height(fish_height).width(fish_weight);
                return;
            }
            if ($(this).hasClass('fa-sushi-light')) {
                $(this).removeClass('fa-sushi-light');
                $(this).addClass('fa-fishbone-light');
            }
            if ($(this).hasClass('fa-sushi-dark')) {
                $(this).removeClass('fa-sushi-dark');
                $(this).addClass('fa-fishbone-dark');
            }
            $(this).height(fish_height).width(fish_weight);
            $(this).removeClass('side-fish');
            return;
        });
    });
</script>
