<?php
require_once 'view_lang_define/content_define.php';
$targetTextPath = getcwd() . '/public/data/' . $this->langFlag . '/home_intro.txt';
$conditionsPath = getcwd() . '/public/data/keyword_link_pair.txt';
?>
<canvas>
</canvas>
<div class="title-area">
    <h2 class="title-text">
        <?= $indexTitle[$this->langFlag] ?>
    </h2>
</div>
<br/>
<div class="content-area">
    <?= nl2br($this->contentHelper($targetTextPath, $conditionsPath)) ?>
</div>
